### PR TITLE
Including a "how it works" section and a printscreen

### PR DESCRIPTION
**Pull request by fabriciorissetto**
Preview here:

https://github.com/fabriciorissetto/merlin

### CODE REVIEW

**Comment by klukule** [comment]
Not merging... I'm working on this using WIKI "module" on github :) and the informations provided are not 100% correct... but thanks for trying

**Comment by fabriciorissetto** [comment]
No problem. I noticed the Wiki, but the problem with wiki is that people can't contribute to it. And this is the main proposal of github. What do you thing about moving the Wiki content to readme? About the parts that are not 100% corret, can you help me pointing what should be corrected or improved?

**Comment by fabriciorissetto** [comment]
Another point, what do you think about merge just the screenshot?

**Comment by klukule** [comment]
Well I have scheduled finishing of the guide and more for tomorrow... and I'm going to stick with WIKI, but you can always contact me on discord or via Issues with your ideas (that counts for everyone) and I can modify it :D

**Pull request closed without merging**
